version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - node -v
      - npm ci
  build:
    commands:
      - npm test

reports:
  jest-reports:
    files:
      - test-result.xml
    file-format: JUNITXML
    base-directory: reports
  coverage-report:
    files:
      - 'coverage/clover.xml'
    file-format: 'CLOVERXML'
    